apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: label-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: label-app
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo-name
#  labels:
#    app: demo-service
spec:
  replicas: 1
  template:
    metadata:
      name: demo-app
      labels:
        app: label-app
    spec:
      containers:
        - name: container-name
          image: kimtaesoo/test:1.1
          ports:
          - containerPort: 8080
